import os
import re
import sys

# Configuration
TARGET_DIR = r"C:\Users\wjjo\Desktop\글도비\projects\팽가 망나니 가문 재건\drafts"
REPORT_FILE = r"C:\Users\wjjo\Desktop\글도비\projects\팽가 망나니 가문 재건\correction.md"

# Patterns & Terms
REGEX_ENGLISH = re.compile(r'[a-zA-Z]+')
REGEX_NUMBERS = re.compile(r'[0-9]+')

# Scientific / Modern / Foreign terms suited for Wuxia correction
# This list is used by Sub-Agents to detect issues.
MODERN_TERMS = {
    # [Science/Physics]
    "질량": ["무게", "천근의 무게", "짓누르는 힘"],
    "원심력": ["회전력", "기세", "휘두르는 힘"],
    "관성": ["흐름", "기세", "여력"],
    "중력": ["땅의 기운", "자연의 섭리", "아래로 향하는 힘"],
    "부피": ["크기", "덩어리"],
    "밀도": ["단단함", "응축된 기운"],
    "3차원": ["입체적", "사방팔방"],
    "격자": ["바둑판", "그물"],
    "포물선": ["곡선", "무지개", "활골"],
    "수직": ["직하", "곧장"],
    "입자": ["알갱이", "먼지", "티끌"],
    "진동": ["울림", "떨림", "파동"],
    "반경": ["범위", "거리", "안쪽"],
    "충격량": ["충격", "타격", "반동"],
    "에너지": ["기운", "힘", "내력"],
    "메커니즘": ["이치", "원리", "구조"],
    "설계": ["안배", "계획", "포석"],
    
    # [Medical/Anatomy]
    "심방": ["심장", "심맥"],
    "심실": ["심장"],
    "전정기관": ["귓속", "평형감각"],
    "근섬유": ["근육", "힘줄", "살"],
    "대동맥": ["큰 혈관", "기혈"],
    "아드레날린": ["흥분", "투기"],
    "도파민": ["쾌락", "희열"],
    "트라우마": ["심마", "악몽", "상처"],
    
    # [Units/Numbers]
    "미터": ["장", "척", "보"],
    "킬로미터": ["리"],
    "그램": ["냥", "돈"],
    "킬로그램": ["근", "관"],
    "톤": ["천근", "만근"],
    "초": ["찰나", "눈 깜짝할 새"], # 0.1초 등
    "분": ["각", "식경"],
    "시간": ["시진"],
    "제로": ["전무", "없음", "공(空)"],
    "마이너스": ["음(陰)", "부족"],
    "플러스": ["양(陽)", "더함"],
    
    # [Modern Objects/Concepts]
    "계산기": ["주판", "타산"],
    "댐": ["제방", "둑"],
    "풍선": ["부레", "공기주머니"],
    "나사": ["못"],
    "스프링": ["용수철", "탄력"],
    "엔진": ["심장", "동력"],
    "배터리": ["기운", "내공"],
    "카메라": ["눈", "시선"],
    "렌즈": ["눈", "시야"],
    "스위치": ["기관", "장치"],
    "버튼": ["단추", "기관"],
    "용돈": ["용전", "술값", "유흥비"],
    "안전지대": ["피난처", "안전한 곳"],
    "신호탄": ["봉화", "신호"],
    "투기장": ["비무장", "싸움터"],
    "콜": ["좋다", "수락한다"],
}

class SubAgent:
    def __init__(self, name: str, files: list):
        self.name = name
        self.files = files
        self.findings = {}  # {filename: [{line_num, original, alternatives...}]}

    def analyze(self):
        print(f"🤖 [{self.name}] Assigned {len(self.files)} files. Starting analysis...")
        for file_path in self.files:
            filename = os.path.basename(file_path)
            # print(f"  - [{self.name}] Reading {filename}...")
            
            try:
                with open(file_path, 'r', encoding='utf-8') as f:
                    lines = f.readlines()
            except Exception as e:
                print(f"  !Error reading {filename}: {e}")
                continue

            file_findings = []
            
            for i, line in enumerate(lines):
                line_issues = self._check_line(line)
                if line_issues:
                    for issue in line_issues:
                        file_findings.append({
                            'line': i + 1,
                            'original_text': line.strip(),
                            'issue_term': issue['term'],
                            'suggestions': issue['suggestions']
                        })
            
            if file_findings:
                self.findings[file_path] = file_findings
                print(f"  ✓ [{self.name}] found {len(file_findings)} issues in {filename}.")
            else:
                print(f"  - [{self.name}] found no issues in {filename}.")

    def _check_line(self, line):
        issues = []
        # Check Modern Terms map
        for term, suggestions in MODERN_TERMS.items():
            if term in line:
                issues.append({'term': term, 'suggestions': suggestions})
        
        # Check explicit English (excluding common file extensions if any appear in text)
        english_matches = REGEX_ENGLISH.findall(line)
        if english_matches:
            # Filter reasonably (ignore single chars sometimes? No, strict for now)
            pass
            # For simplicity in this report, focusing on the Dictionary detections primarily as requested by the specific examples in prompt history.
            # But let's add 'English' if found.
            # (Skipping for now to match the user's specific requested style of 'Modern/Foreign concepts')
            
        return issues

class ChiefEditor:
    def __init__(self, agents: list):
        self.agents = agents

    def collect_and_publish(self):
        print(f"\n👑 [Chief Editor] Collecting reports from {len(self.agents)} Sub-Agents...")
        
        with open(REPORT_FILE, 'w', encoding='utf-8') as f:
            f.write("# 교정 보고서 (Correction Report)\n")
            f.write(f"**Generated by:** Chief Editor & {len(self.agents)} Sub-Agents\n")
            f.write(f"**Target:** {TARGET_DIR}\n\n")

            for agent in self.agents:
                f.write(f"### 🕵️ {agent.name} Report\n")
                if not agent.findings:
                    f.write("No issues found.\n\n")
                    continue
                
                for file_path, issues in agent.findings.items():
                    filename = os.path.basename(file_path)
                    f.write(f"#### 📄 {filename}\n")
                    f.write("| No | Issue | Original Sentence | Suggestion 1 | Suggestion 2 |\n")
                    f.write("| :-- | :--- | :--- | :--- | :--- |\n")
                    
                    for idx, issue in enumerate(issues, 1):
                        orig = issue['original_text']
                        # Bolding the issue term in original text
                        highlighted_orig = orig.replace(issue['issue_term'], f"**{issue['issue_term']}**")
                        # Truncate if too long
                        if len(highlighted_orig) > 60:
                             highlighted_orig = highlighted_orig[:60] + "..."
                        
                        sugg1 = f"**{issue['suggestions'][0]}**" if len(issue['suggestions']) > 0 else ""
                        sugg2 = f"**{issue['suggestions'][1]}**" if len(issue['suggestions']) > 1 else ""
                        
                        f.write(f"| {idx} | {issue['issue_term']} | {highlighted_orig} | {sugg1} | {sugg2} |\n")
                    f.write("\n")
                f.write("---\n")
        
        print(f"✅ [Chief Editor] Report saved to: {REPORT_FILE}")

def scan_files(directory):
    files = []
    for root, _, filenames in os.walk(directory):
        for filename in filenames:
            if filename.endswith(".txt"):
                files.append(os.path.join(root, filename))
    return sorted(files)

def main():
    print("--- 🚀 Wuxia Correction Team Assembling ---")
    all_files = scan_files(TARGET_DIR)
    
    if not all_files:
        print("No files found!")
        return

    # Task Allocation (3-3-4 split)
    # files 0-2 (3), 3-5 (3), 6-9 (4)
    group1 = all_files[0:3]
    group2 = all_files[3:6]
    group3 = all_files[6:]
    
    agent1 = SubAgent("Sub_Agent_1", group1)
    agent2 = SubAgent("Sub_Agent_2", group2)
    agent3 = SubAgent("Sub_Agent_3", group3)
    
    team = [agent1, agent2, agent3]
    
    # Execute Analysis
    for agent in team:
        agent.analyze()
        
    # Aggregate
    chief = ChiefEditor(team)
    chief.collect_and_publish()

if __name__ == "__main__":
    main()
